spring:
  application:
    name: rabbitmq-springboot
  rabbitmq:
    host: 127.0.0.1
    port: 5673
    username: ems
    password: 123
    virtual-host: /ems
    listener:
      simple:
        acknowledge-mode: manual #开启手动Ack

